export default {
    STRING_KY: `"`,
    TERMINATION_KY: '.',
    DECLARATION_KY: 'let',
    ASSIGNMENT_KY: 'be',
    FUNCTION_KY: 'do:',
    FUNCTION_CALL_KY: 'run',
    FUNCTION_ARGUMENT_KY: 'with',
    FUNCTION_ARGUMENT_RENAME_KY: 'as',
    FUNCTION_ARGUMENT_SEPARATOR_KY: ',',
    FUNCTION_TERMINATION_KY: 'stop',
    AND_OPERATOR: 'and',
    OR_OPERATOR: 'or',
    EQUAL_OPERATOR: 'isequalto',
    LESS_THAN_OPERATOR: 'islessthan',
    LESS_THAN_EQUAL_OPERATOR: 'islessthanorequalto',
    GREATER_THAN_OPERATOR: 'isgreaterthan',
    GREATER_THAN_EQUAL_OPERATOR: 'isgreaterthanorequalto',
    ADDITION_OPERATOR: 'plus',
    SUBTRACTION_OPERATOR: 'minus',
    MULTIPLICATION_OPERATOR: 'times',
    DIVISION_OPERATOR: 'divided by',
    IF_DECLARATION_KY: 'if',
    ELSE_DECLARATION_KY: 'otherwiseif',
    PRINT_KY: 'say',
    TRUE_KY: 'true',
    FALSE_KY: 'false',
}
